# Generated by Django 4.2 on 2023-04-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=80, verbose_name='Make')),
                ('model', models.CharField(max_length=80, verbose_name='Model')),
                ('color', models.CharField(max_length=80, verbose_name='Color')),
                ('car_body', models.IntegerField(choices=[(1, 'Coupe'), (2, 'Sedan'), (3, 'Hatchback'), (4, 'Wagon')], verbose_name='CAR_BODY')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
